In [28]:
import os
import pandas as pd
import numpy as np

In [29]:
def load_csv(path):
    full = os.path.join('diabetes', path)
    return pd.read_csv(full)

In [30]:
original = load_csv('diabetic_data_balanced.csv')
pd.set_option('display.max_columns', None)

original.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [31]:
original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 50 columns):
encounter_id                9999 non-null int64
patient_nbr                 9999 non-null int64
race                        9819 non-null object
gender                      9999 non-null object
age                         9999 non-null object
weight                      300 non-null object
admission_type_id           9999 non-null int64
discharge_disposition_id    9999 non-null int64
admission_source_id         9999 non-null int64
time_in_hospital            9999 non-null int64
payer_code                  235 non-null object
medical_specialty           6362 non-null object
num_lab_procedures          9999 non-null int64
num_procedures              9999 non-null int64
num_medications             9999 non-null int64
number_outpatient           9999 non-null int64
number_emergency            9999 non-null int64
number_inpatient            9999 non-null int64
diag_1                      9994 non-null object
diag_2                      9954 non-null object
diag_3                      9764 non-null object
number_diagnoses            9999 non-null int64
max_glu_serum               9999 non-null object
A1Cresult                   9999 non-null object
metformin                   9999 non-null object
repaglinide                 9999 non-null object
nateglinide                 9999 non-null object
chlorpropamide              9999 non-null object
glimepiride                 9999 non-null object
acetohexamide               9999 non-null object
glipizide                   9999 non-null object
glyburide                   9999 non-null object
tolbutamide                 9999 non-null object
pioglitazone                9999 non-null object
rosiglitazone               9999 non-null object
acarbose                    9999 non-null object
miglitol                    9999 non-null object
troglitazone                9999 non-null object
tolazamide                  9999 non-null object
examide                     9999 non-null object
citoglipton                 9999 non-null object
insulin                     9999 non-null object
glyburide-metformin         9999 non-null object
glipizide-metformin         9999 non-null object
glimepiride-pioglitazone    9999 non-null object
metformin-rosiglitazone     9999 non-null object
metformin-pioglitazone      9999 non-null object
change                      9999 non-null object
diabetesMed                 9999 non-null object
readmitted                  9999 non-null object
dtypes: int64(13), object(37)
memory usage: 3.8+ MB

In [34]:
original.describe(include='all')

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
count,9.999000e+03,9.999000e+03,9819,9999,9999,300,9999.000000,9999.000000,9999.000000,9999.000000,235,6362,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9994,9954,9764,9999.000000,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999
unique,NaN,NaN,5,2,10,8,NaN,NaN,NaN,NaN,10,49,NaN,NaN,NaN,NaN,NaN,NaN,441,421,462,NaN,4,4,4,4,2,2,4,1,4,4,2,4,4,3,2,2,2,1,1,4,2,1,1,1,1,2,2,3
top,NaN,NaN,Caucasian,Female,[70-80),[75-100),NaN,NaN,NaN,NaN,MC,InternalMedicine,NaN,NaN,NaN,NaN,NaN,NaN,414,428,250,NaN,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
freq,NaN,NaN,7181,5390,2693,128,NaN,NaN,NaN,NaN,129,1974,NaN,NaN,NaN,NaN,NaN,NaN,959,671,1105,NaN,9048,8177,8415,9906,9993,9983,9632,9999,8636,8585,9993,9599,9408,9964,9998,9996,9986,9999,9999,5087,9993,9999,9999,9999,9999,6093,7564,3333
mean,3.216415e+07,2.616384e+07,NaN,NaN,NaN,NaN,2.455546,4.733073,6.721972,4.838984,NaN,NaN,46.870087,1.445645,15.303830,0.109311,0.064906,0.659166,NaN,NaN,NaN,6.892089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.289500e+07,3.362519e+07,NaN,NaN,NaN,NaN,1.865877,6.791574,4.995468,3.167283,NaN,NaN,18.128148,1.724649,7.915417,0.589934,0.442184,1.351151,NaN,NaN,NaN,2.008747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.252200e+04,1.350000e+02,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,NaN,NaN,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.622300e+07,2.425828e+06,NaN,NaN,NaN,NaN,1.000000,1.000000,2.000000,2.000000,NaN,NaN,35.000000,0.000000,10.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.698463e+07,8.794098e+06,NaN,NaN,NaN,NaN,2.000000,1.000000,7.000000,4.000000,NaN,NaN,47.000000,1.000000,14.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,3.790203e+07,3.230309e+07,NaN,NaN,NaN,NaN,3.000000,6.000000,7.000000,7.000000,NaN,NaN,59.000000,2.000000,19.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,9.448424e+07,1.151968e+08,NaN,NaN,NaN,NaN,8.000000,25.000000,20.000000,14.000000,NaN,NaN,114.000000,6.000000,62.000000,12.000000,22.000000,17.000000,NaN,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
np.any(original['metformin-pioglitazone'] != 'No')